### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating '$.expr.createPseudo') on line 17 with jQuery 1.7.2

### ISSUE THREAD

**Issue by eablokker** [silviomoreto/bootstrap-select#307]
TypeError: 'undefined' is not a function (evaluating '$.expr.createPseudo') in bootstrap-select.js on line 17. Using jQuery 1.7.2.

I just updated to the latest version (1.3.1) and I'm getting this error. Does not work at all in jQuery 1.7.2 and below. It previously worked with jQuery 1.7.2. I don't see jQuery or which version listed as a dependency in the docs.

Here's a fiddle: http://jsfiddle.net/wrbWz/
Check the console for the error.
